//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SzerszamgepKereskedelem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class felhasznalo
    {
        public int Id { get; set; }
        public string felhasznalonev { get; set; }
        public string jelszo { get; set; }
        public bool modositas { get; set; }
        public string vezeteknev { get; set; }
        public string keresztnev { get; set; }
    }
}
