//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SzerszamgepKereskedelem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class megrendeles
    {
        public int id { get; set; }
        public int gep_Id { get; set; }
        public int vevo_Id { get; set; }
        public int beszerzes_Id { get; set; }
        public int eladas_Id { get; set; }
    
        public virtual beszerzesek beszerzesek { get; set; }
        public virtual eladasok eladasok { get; set; }
        public virtual gepek gepek { get; set; }
        public virtual vevok vevok { get; set; }
    }
}
