//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SzerszamgepKereskedelem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class szerszamgepContext : DbContext
    {
        public szerszamgepContext()
            : base("name=szerszamgepContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beszerzesek> beszerzesek { get; set; }
        public virtual DbSet<eladasok> eladasok { get; set; }
        public virtual DbSet<felhasznalo> felhasznalo { get; set; }
        public virtual DbSet<gepek> gepek { get; set; }
        public virtual DbSet<megrendeles> megrendeles { get; set; }
        public virtual DbSet<vevok> vevok { get; set; }
    }
}
